# Form implementation generated from reading ui file 'baseUi.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 213)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(20, 60, 194, 22))
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2001, 9, 14), QtCore.QTime(8, 0, 0)))
        self.dateTimeEdit.setTime(QtCore.QTime(8, 0, 0))
        self.dateTimeEdit.setMaximumDate(QtCore.QDate(2024, 12, 31))
        self.dateTimeEdit.setMinimumDate(QtCore.QDate(2001, 1, 1))
        self.dateTimeEdit.setMinimumTime(QtCore.QTime(4, 00, 00))
        self.dateTimeEdit.setMaximumTime(QtCore.QTime(20, 00, 00))
        self.dateTimeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.Section.DaySection)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setCurrentSectionIndex(0)
        self.dateTimeEdit.setTimeSpec(QtCore.Qt.TimeSpec.LocalTime)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.labelDate = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelDate.setGeometry(QtCore.QRect(20, 30, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName("labelDate")
        self.Result = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.Result.setGeometry(QtCore.QRect(20, 130, 101, 31))
        self.Result.setObjectName("Result")
        self.enterButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.enterButton.setGeometry(QtCore.QRect(250, 60, 111, 31))
        self.enterButton.setObjectName("enterButton")
        self.labelResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(20, 100, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dateTimeEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy H:mm"))
        self.labelDate.setText(_translate("MainWindow", "Enter date:"))
        self.Result.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.enterButton.setText(_translate("MainWindow", "Enter"))
        self.labelResult.setText(_translate("MainWindow", "Prediction of the price of share in selected day:"))
